export const WORD_LIST = [
    { word: "ARITZIA", clue: "Beige aesthetic that drains the wallet" },
    { word: "BADEMIYA", clue: "Late night priesthood of kebabs" },
    { word: "HOCKEY", clue: "Canada's Religion on ice" },
    { word: "MUSICALS", clue: "Broadway's love language" },
    { word: "BUILDINGS", clue: "Concrete sky-scrapers you admire" },
    { word: "LEATHERPANTS", clue: "Ross Geller's struggle, your style staple" },
    { word: "JUSTINBIEBER", clue: "The kid from Stratford" },
    { word: "SUSHI", clue: "Deconstructed aquarium dinner" },
    { word: "MAXVERSTAPPEN", clue: "The flying Dutchman on existing tracks" },
    { word: "LAVIEENROSE", clue: "The flushed hue of my world when we're intimate" },
    { word: "SCENARIOS", clue: "Hypothetical question time" },
    { word: "SKIING", clue: "Controlled avalanche evasion" },
    { word: "TIMHORTONS", clue: "Double-double dealer" },
    { word: "SAIF", clue: "The architect of this puzzle ;)" },
    { word: "PILATES", clue: "Pulse, hold, shake... embrace the burn" },
    { word: "MAGNETICNAILS", clue: "Cat-eye texture at your fingertips" },
];
